Zet xml-apis op provided
Vanwege foutmelding:

java.lang.IllegalStateException: You are running with invalid JAXP api or implementation. JAXP api/implementation of version 1.3.1 (included in JDK6) or higher is required. In case you are using ant, make sure ant 1.7.0 or higher is used - older versions of ant contain JAXP api/impl version 1.2 (in xml-apis.jar). If you want to keep using older ant versions, you have to configure it to use higher the JAXP api/impl versions.
	com.sun.xml.internal.bind.v2.util.XmlFactory.createTransformerFactory(Unknown Source)